### ISSUE TITLE
same modulename from different authors

### ISSUE THREAD

**Issue by fonk** [rodjek/librarian-puppet#277]
Hi,

what's the best practice, if I have a Module theforeman-foreman_proxy which depends on theforeman-dns (which i don't need nor use) and i'd like to use ajjahn-dns from https://github.com/ajjahn/puppet-dns.git ? At the moment I get theforeman-dns by running librarian with this configuration:

mod 'theforeman-foreman_proxy', '2.1.0'
mod 'ajjahn-dns',
  :git => 'https://github.com/ajjahn/puppet-dns'

Best regards,
Frank

**Comment by stevelacey** [comment]
On a similar note, am I the only that also found that if you have modules requiring different dependencies with the same name – librarian will happily plod along, download one... then overwrite it with the other – no error.

If what I am seeing is correct, that is crazy.

Example:

```
mod "puppetlabs-concat", "~> 1.2.0"
mod "puppetlabs/postgresql", "~> 2.4.1"
```

This left me with `ripienaar-concat (0.2.0)` – because I was using old postgresql module that requires it... this not causing an error in dependency resolution is nuts. NB: I saw whilst it was doing an update run – it'd install puppetlabs-concat first, then overwrite it.

**Comment by carlossg** [comment]
Exclusions added in 1f3903e
